scalar Date

enum Permission {
  InfoUpdate
  AnnouncementCreate
  AnnouncementRead
  ProblemsCreate
  ProblemsRead
  ProblemsReadDisabled
  ProblemsUpdate
  ProblemsDelete
  UsersInvite
  UsersPermissionsUpdate
  UsersDelete
  ProfilesRead
}

type User {
  id: String!
  contest: Contest!
  username: String!
  email: String!
  name: String!

  permissions: [Permission!]!
  profile: Profile!
}

enum GenderType {
  Male
  Female
}

enum ShirtSizeType {
  XS
  S
  M
  L
  XL
  XXL
}

type Profile {
  gender: GenderType
  shirtSize: ShirtSizeType
  address: String
}

type Language {
  id: String!
  name: String!
}

type Contest {
  id: String!
  shortId: String!
  name: String!
  shortDescription: String
  description: String
  startTime: Date
  freezed: Boolean
  finishTime: Date
  permittedLanguages: [Language!]!

  users(email: String, username: String): [User!]!
}

type Query {
  user: User!
  userById(id: String!): User!
  userByEmail(contestId: String!, email: String!): User!
  userByUsername(contestId: String!, username: String!): User!

  contest: Contest!
  contestById(id: String!): Contest!
  contestByShortId(shortId: String!): Contest!

  languages: [Language!]!
  languageById(id: String!): Language!

  profile: Profile!
  userProfile(userId: String!): Profile!
}

type Mutation {
  login(contestId: String!, email: String!, password: String!): String!
  setMyProfile(
    gender: GenderType
    shirtSize: ShirtSizeType
    address: String
  ): Profile!
}
