version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6

jobs:
  build-ugrade-server:
    working_directory: ~/ugrade/server
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout:
          path: ~/ugrade
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          name: Restore Python Packages
          keys:
            - pip-packages-{{ checksum "Pipfile.lock" }}
      - run:
          name: "Install Dependencies"
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          name: Save Python Package Cache
          key: pip-packages-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: test
          command: pipenv run python py.test
      - store_test_results:
          path: htmlcov

  install-ugrade-web:
    working_directory: ~/ugrade/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/ugrade
          paths:
            - web/node_modules

  test-ugrade-web:
    working_directory: ~/ugrade/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - attach_workspace:
          at: ~/ugrade
      - run:
          name: test
          command: yarn test

  build-ugrade-web:
    working_directory: ~/ugrade/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/ugrade
      - attach_workspace:
          at: ~/ugrade
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ~/ugrade
          paths:
            - web/build

  build-ugrade-web-image:
    executor: docker-publish/docker
    working_directory: ~/ugrade/web
    steps:
      - checkout:
          path: ~/ugrade
      - attach_workspace:
          at: ~/ugrade
      - setup_remote_docker
      - docker-publish/check
      - docker-publish/build:
          image: jauhararifin/ugrade-web
      - docker-publish/deploy:
          image: jauhararifin/ugrade-web

workflows:
  version: 2
  ugrade:
    jobs:
      - build-ugrade-server
      - install-ugrade-web
      - test-ugrade-web:
          requires:
            - install-ugrade-web
      - build-ugrade-web:
          requires:
            - install-ugrade-web
            - test-ugrade-web
      - build-ugrade-web-image:
          requires:
            - build-ugrade-web
