version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6

jobs:
  build-ugrade-server:
    working_directory: ~/ugrade/server
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout:
          path: ~/ugrade
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          name: Restore Python Packages
          keys:
            - pip-packages-{{ checksum "Pipfile.lock" }}
      - run:
          name: "Install Dependencies"
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          name: Save Python Package Cache
          key: pip-packages-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: test
          command: pipenv run py.test
      - store_test_results:
          path: htmlcov

workflows:
  version: 2
  ugrade:
    jobs:
      - build-ugrade-server
