# Generated by Django 2.1.7 on 2019-03-30 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('IE', 'Internal Error'), ('CE', 'Compilation Error'), ('RTE', 'Run Time Error'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=32)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('IE', 'Internal Error'), ('CE', 'Compilation Error'), ('RTE', 'Run Time Error'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=32)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission')),
            ],
        ),
        migrations.AddField(
            model_name='grading',
            name='grading_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='grading.GradingGroup'),
        ),
        migrations.AddField(
            model_name='grading',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.User'),
        ),
    ]
