# Generated by Django 2.1.7 on 2019-04-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='verdict',
            field=models.CharField(choices=[('RTE', 'Run Time Error'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('IE', 'Internal Error'), ('AC', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='gradinggroup',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_groups', to='contests.Submission'),
        ),
        migrations.AlterField(
            model_name='gradinggroup',
            name='verdict',
            field=models.CharField(choices=[('RTE', 'Run Time Error'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('IE', 'Internal Error'), ('AC', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=32),
        ),
    ]
