package rlimit

import (
	"syscall"

	"github.com/jauhararifin/ugrade/sandbox"
	"golang.org/x/xerrors"
)

type defaultRlimit struct {
}

// Set set rlimit of current process
func (*defaultRlimit) Set(rlimitType int, cur, max uint64) error {
	var rLimit syscall.Rlimit
	err := syscall.Getrlimit(rlimitType, &rLimit)
	if err != nil {
		return xerrors.Errorf("cannot get rlimit: %w", err)
	}

	rLimit.Max = max
	rLimit.Cur = cur

	if err := syscall.Setrlimit(rlimitType, &rLimit); err != nil {
		return xerrors.Errorf("cannot set rlimit: %w", err)
	}

	return nil
}

// LimitOpenFile limit the number of open file of current processs.
func (rlim *defaultRlimit) LimitOpenFile(nopenfile uint64) error {
	if err := rlim.Set(syscall.RLIMIT_NOFILE, nopenfile, nopenfile); err != nil {
		return xerrors.Errorf("cannot set number of open file limit: %w", err)
	}
	return nil
}

// LimitFSize limit the size of file generated by current process.
func (rlim *defaultRlimit) LimitFSize(fsize uint64) error {
	if err := rlim.Set(syscall.RLIMIT_FSIZE, fsize, fsize); err != nil {
		return xerrors.Errorf("cannot set file size limit: %w", err)
	}
	return nil
}

// LimitNProcess limit the number of process creation.
func (rlim *defaultRlimit) LimitNProcess(nproc uint64) error {
	rlimitNProc := 6 // constant of kernel ulimit for limiting fork
	if err := rlim.Set(rlimitNProc, nproc, nproc); err != nil {
		return xerrors.Errorf("cannot set number of process creation: %w", err)
	}
	return nil
}

// LimitStack limit stack size of process.
func (rlim *defaultRlimit) LimitStack(stackSize uint64) error {
	rlimitStack := 3
	if err := rlim.Set(rlimitStack, stackSize, stackSize); err != nil {
		return xerrors.Errorf("cannot set stack size limit: %w", err)
	}
	return nil
}

// New create default implementatoin of `sandbox.RLimit`
func New() sandbox.RLimit {
	return &defaultRlimit{}
}
