# Generated by Django 2.1.7 on 2019-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='grading_size',
            field=models.IntegerField(default=1),
        ),
    ]
