# Generated by Django 2.1.7 on 2019-03-25 14:12

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20190325_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='finishTime',
            new_name='finish_time',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='permittedLanguages',
            new_name='permitted_languages',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='shortDescription',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='shortId',
            new_name='short_id',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='memoryLimit',
            new_name='memory_limit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='outputLimit',
            new_name='output_limit',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='timeLimit',
            new_name='time_limit',
        ),
        migrations.AddField(
            model_name='problem',
            name='short_id',
            field=models.CharField(default='someval', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid'), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='shortId',
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('short_id', 'contest')},
        ),
    ]
