# Generated by Django 2.1.7 on 2019-04-21 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contest_grading_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='grading_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(255)], verbose_name='email'),
        ),
    ]
