# Generated by Django 2.1.7 on 2019-03-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20190325_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_time', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('IE', 'Internal Error'), ('CE', 'Compilation Error'), ('RTE', 'Run Time Error'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=1024)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='grading',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
    ]
