# Generated by Django 2.1.7 on 2019-03-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20190327_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='issuer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contests.User'),
            preserve_default=False,
        ),
    ]
