# Generated by Django 2.1.7 on 2019-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_submission_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source_code',
            field=models.FileField(default='', upload_to='submissions'),
            preserve_default=False,
        ),
    ]
