# Generated by Django 2.1.7 on 2019-03-30 02:39

import contests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_submission_source_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='submission',
        ),
        migrations.AlterField(
            model_name='submission',
            name='source_code',
            field=models.FileField(upload_to=contests.models.upload_path),
        ),
        migrations.DeleteModel(
            name='Grading',
        ),
    ]
