package worker

import "context"

// SourceCode represent program's source code.
type SourceCode struct {
	Path     string
	Language string
}

// JobSpec represent job specification from ugrade server.
type JobSpec struct {
	TCGen      SourceCode
	Solution   SourceCode
	Checker    SourceCode
	Submission SourceCode

	TimeLimit   uint64
	OutputLimit uint64
	MemoryLimit uint64
	Tolerance   float64
}

// JobResult represent job result generated by worker.
type JobResult struct {
	Verdict string
}

// Solver solve job and gives result.
type Solver interface {
	Solve(ctx context.Context, spec JobSpec) (*JobResult, error)
}
